# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSInjectFlutter' do
    pod 'AFNetworking', '~> 3.2.1'
    flutter_application_path = '../my_flutter/'
        eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
