# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFlutterml' do
pod 'Firebase/Core'
flutter_application_path = '../my_flutter/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
