# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'flutterboostdemo' do

  pod 'FDFullscreenPopGesture', '1.1'

#  flutter_application_path = '../my_flutter/'
#  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
#  install_all_flutter_pods(flutter_application_path)

  flutter_application_path = '../my_flutter/'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end

